# Model Configuration
model:
  name: "EfficientNetV2B0"
  img_size: [192, 192]
  num_classes: 5
  attention:
    num_heads: 2
    key_dim: 32
  dense_layers:
    neurons: 128
    dropout: 0.5
  regularization:
    l2_factor: 0.0001
    dropout: 0.3

# Training Configuration
training:
  batch_size: 4
  epochs: 10
  learning_rate: 0.001
  validation_split: 0.2
  class_weights: true
  early_stopping:
    patience: 3
    min_delta: 0.001
  reduce_lr:
    factor: 0.2
    patience: 2
    min_lr: 0.000001

# Data Configuration
data:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  classes:
    - "Bacterial Pneumonia"
    - "Corona Virus Disease"
    - "NORMAL"
    - "Tuberculosis"
    - "Viral Pneumonia"
  augmentation:
    rotation_range: 15
    width_shift_range: 0.1
    height_shift_range: 0.1
    shear_range: 0.1
    zoom_range: 0.1
    horizontal_flip: true

# Output Configuration
output:
  model_dir: "output/models"
  results_dir: "output/results"
  visualizations_dir: "output/visualizations"
  tensorboard_dir: "output/tensorboard" 